// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgrpkdtlnlxifdlqrcay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJncnBrZHRsbmx4aWZkbHFyY2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMzExMjYsImV4cCI6MjA1ODkwNzEyNn0.3aH96fqefHt4t4VcGtMYSGoonRhJwOcZ-OrCfE84k6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);